- id: '1707650979263'
  alias: Koniec prania
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.wtyczka_do_pralki_power
    for:
      hours: 0
      minutes: 0
      seconds: 20
    below: 3
  condition: []
  action:
  - service: notify.mobile_app_sm_g780g
    metadata: {}
    data:
      message: "Pranie \U0001F970"
  - service: notify.mobile_app_sm_g970f
    metadata: {}
    data:
      message: "Pranie \U0001F970"
  mode: single
- id: '1707755839697'
  alias: Powiadomienie jak Rafal wychodzi z domu
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.rafal
      zone_entity: zone.home
      notify_device: 60d289e8a185f53746d694b216b4808b
- id: '1707755894810'
  alias: Powiedomienie rafal wchodzi
  description: ''
  trigger:
  - platform: zone
    entity_id: person.rafal
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_sm_g780g
    metadata: {}
    data:
      message: Rafal przychodzi do domu
  mode: single
- id: '1707756053365'
  alias: Pow rafal wchodzi do przedszkola
  description: ''
  trigger:
  - platform: zone
    entity_id: person.rafal
    zone: zone.przedszkole
    event: enter
  condition: []
  action:
  - service: notify.mobile_app_sm_g780g
    metadata: {}
    data:
      message: Rafal wchodzi do przedszkola
  mode: single
- id: '1707756092607'
  alias: Powiadomienie do Rafała jak Rafał wychodzi z przedszkola
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.rafal
      zone_entity: zone.przedszkole
      notify_device: 60d289e8a185f53746d694b216b4808b
- id: '1712398093906'
  alias: Wyłącz Łusi lampkę o poranku
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - type: turn_off
    device_id: 7045779a7acd54edd95df0d05976302b
    entity_id: cc4ac43c4ba8cccd5e4119a62ad95c20
    domain: light
  mode: single
- id: '1712443711172'
  alias: Pobudka (dzień roboczy)
  description: ''
  trigger:
  - platform: time
    at: 07:15:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.pobudka_w_sypialni
    metadata: {}
    data: {}
  mode: single
- id: '1712856497767'
  alias: Przygotuj Łusi pokój na spanie
  description: ''
  trigger:
  - platform: tag
    tag_id: ff68e214-19d0-450d-aac1-0aa012ced15f
  condition: []
  action:
  - service: script.1712856352616
    data: {}
  mode: single
- id: '1712856797316'
  alias: Przygotuj Łusi pokój na czytanie bajek
  description: ''
  trigger:
  - platform: tag
    tag_id: 5ac8a1cb-d3a0-4793-88f4-ca70e70aa2b9
  condition: []
  action:
  - service: script.ustaw_lusi_pokoj_na_czytanie_bajek
    metadata: {}
    data: {}
  mode: single
- id: '1713647398131'
  alias: Pobudka (weekend)
  description: ''
  trigger:
  - platform: time
    at: 08:15:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: script.pobudka_w_sypialni
    metadata: {}
    data: {}
  mode: single
- id: '1713873043917'
  alias: Powiadomienie do Rafała jak Emilka wychodzi z przedszkola
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      zone_entity: zone.przedszkole
      notify_device: 60d289e8a185f53746d694b216b4808b
      person_entity: person.emilka
- id: '1719157857647'
  alias: Uruchom radio 357 po zeskanowaniu tagu w kuchni
  description: ''
  trigger:
  - platform: tag
    tag_id: 408d9193-49b1-4b87-9bce-1b17096eb6aa
  condition: []
  action:
  - service: script.uruchom_radio_357_kuchnia
    metadata: {}
    data: {}
  mode: single
- id: '1719166705957'
  alias: Minutnik 2m w kuchni na zeskanowanie tagu
  description: ''
  trigger:
  - platform: tag
    tag_id: 745cca0e-7995-47fa-9704-10f3f0a3a188
  condition: []
  action:
  - service: script.minutnik_2m_kuchnia
    metadata: {}
    data: {}
  mode: single
- id: '1719166743068'
  alias: Minutnik 3m kuchnia
  description: ''
  trigger:
  - platform: tag
    tag_id: 6ee31994-4d08-4027-85b6-1153b0275d52
  condition: []
  action:
  - service: script.minutnik_3m_kuchnia
    metadata: {}
    data: {}
  mode: single
- id: '1719173929529'
  alias: Przeczytaj poranny status po zeskanowaniu tagu
  description: ''
  trigger:
  - platform: tag
    tag_id: 37ac15b0-c3a9-464c-9be5-6b4c225e49f5
  condition: []
  action:
  - service: script.poranny_status
    metadata: {}
    data: {}
  mode: single
- id: '1719173980386'
  alias: Przeczytaj wieczorny status po zeskanowaniu tagu
  description: ''
  trigger:
  - platform: tag
    tag_id: 52646e93-adcb-42b9-8c6d-dd7f49085289
  condition: []
  action:
  - service: script.gadanie
    metadata: {}
    data: {}
  mode: single
